In [1]:
import numpy as np 
import pandas as pd 
%matplotlib notebook
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import VotingClassifier
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_score
from sklearn.svm import SVC
from sklearn.ensemble import AdaBoostClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import precision_score, recall_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import sklearn.metrics as metrics
from sklearn.metrics import classification_report
import warnings
warnings.filterwarnings('ignore')
import os
import pickle

In [5]:
data=pd.read_csv('C:/Users/aryan/ARYANSH/DYPU/TE mini project/breast cancer/Breast-Cancer-Detection-Web-App-main/breast_cancer_dataset.csv')
print(data)

           id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M        17.99         10.38          122.80     1001.0   
1      842517         M        20.57         17.77          132.90     1326.0   
2    84300903         M        19.69         21.25          130.00     1203.0   
3    84348301         M        11.42         20.38           77.58      386.1   
4    84358402         M        20.29         14.34          135.10     1297.0   
..        ...       ...          ...           ...             ...        ...   
564    926424         M        21.56         22.39          142.00     1479.0   
565    926682         M        20.13         28.25          131.20     1261.0   
566    926954         M        16.60         28.08          108.30      858.1   
567    927241         M        20.60         29.33          140.10     1265.0   
568     92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compa

In [6]:
data.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

In [7]:
data.diagnosis

0      M
1      M
2      M
3      M
4      M
      ..
564    M
565    M
566    M
567    M
568    B
Name: diagnosis, Length: 569, dtype: object

In [8]:
data.head(5)

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [9]:
data.shape

(569, 33)

In [10]:
data=data.drop(['id'], axis=1)
data.columns

Index(['diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

In [21]:
data=data.drop(['Unnamed: 32'], axis=1)
data.columns

Index(['diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst'],
      dtype='object')

In [22]:
data.describe()

radius_mean  texture_mean  perimeter_mean    area_mean  \
count   569.000000    569.000000      569.000000   569.000000   
mean     14.127292     19.289649       91.969033   654.889104   
std       3.524049      4.301036       24.298981   351.914129   
min       6.981000      9.710000       43.790000   143.500000   
25%      11.700000     16.170000       75.170000   420.300000   
50%      13.370000     18.840000       86.240000   551.100000   
75%      15.780000     21.800000      104.100000   782.700000   
max      28.110000     39.280000      188.500000  2501.000000   

       smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
count       569.000000        569.000000      569.000000           569.000000   
mean          0.096360          0.104341        0.088799             0.048919   
std           0.014064          0.052813        0.079720             0.038803   
min           0.052630          0.019380        0.000000             0.000000   
25%           0.086370          0.064920        0.029560             0.020310   
50%           0.095870          0.092630        0.061540             0.033500   
75%           0.105300          0.130400        0.130700             0.074000   
max           0.163400          0.345400        0.426800             0.201200   

       symmetry_mean  fractal_dimension_mean  ...  radius_worst  \
count     569.000000              569.000000  ...    569.000000   
mean        0.181162                0.062798  ...     16.269190   
std         0.027414                0.007060  ...      4.833242   
min         0.106000                0.049960  ...      7.930000   
25%         0.161900                0.057700  ...     13.010000   
50%         0.179200                0.061540  ...     14.970000   
75%         0.195700                0.066120  ...     18.790000   
max         0.304000                0.097440  ...     36.040000   

       texture_worst  perimeter_worst   area_worst  smoothness_worst  \
count     569.000000       569.000000   569.000000        569.000000   
mean       25.677223       107.261213   880.583128          0.132369   
std         6.146258        33.602542   569.356993          0.022832   
min        12.020000        50.410000   185.200000          0.071170   
25%        21.080000        84.110000   515.300000          0.116600   
50%        25.410000        97.660000   686.500000          0.131300   
75%        29.720000       125.400000  1084.000000          0.146000   
max        49.540000       251.200000  4254.000000          0.222600   

       compactness_worst  concavity_worst  concave points_worst  \
count         569.000000       569.000000            569.000000   
mean            0.254265         0.272188              0.114606   
std             0.157336         0.208624              0.065732   
min             0.027290         0.000000              0.000000   
25%             0.147200         0.114500              0.064930   
50%             0.211900         0.226700              0.099930   
75%             0.339100         0.382900              0.161400   
max             1.058000         1.252000              0.291000   

       symmetry_worst  fractal_dimension_worst  
count      569.000000               569.000000  
mean         0.290076                 0.083946  
std          0.061867                 0.018061  
min          0.156500                 0.055040  
25%          0.250400                 0.071460  
50%          0.282200                 0.080040  
75%          0.317900                 0.092080  
max          0.663800                 0.207500  

[8 rows x 30 columns]

In [23]:
data.isnull().any()

diagnosis                  False
radius_mean                False
texture_mean               False
perimeter_mean             False
area_mean                  False
smoothness_mean            False
compactness_mean           False
concavity_mean             False
concave points_mean        False
symmetry_mean              False
fractal_dimension_mean     False
radius_se                  False
texture_se                 False
perimeter_se               False
area_se                    False
smoothness_se              False
compactness_se             False
concavity_se               False
concave points_se          False
symmetry_se                False
fractal_dimension_se       False
radius_worst               False
texture_worst              False
perimeter_worst            False
area_worst                 False
smoothness_worst           False
compactness_worst          False
concavity_worst            False
concave points_worst       False
symmetry_worst             False
fractal_di

In [24]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   diagnosis                569 non-null    object 
 1   radius_mean              569 non-null    float64
 2   texture_mean             569 non-null    float64
 3   perimeter_mean           569 non-null    float64
 4   area_mean                569 non-null    float64
 5   smoothness_mean          569 non-null    float64
 6   compactness_mean         569 non-null    float64
 7   concavity_mean           569 non-null    float64
 8   concave points_mean      569 non-null    float64
 9   symmetry_mean            569 non-null    float64
 10  fractal_dimension_mean   569 non-null    float64
 11  radius_se                569 non-null    float64
 12  texture_se               569 non-null    float64
 13  perimeter_se             569 non-null    float64
 14  area_se                  5

In [25]:
M,B=data['diagnosis'].value_counts()
print('No. of malignant cases: ' ,M)
print('No. of benign cases: ' ,B)
sns.catplot(x='diagnosis',kind='count',data=data, palette="husl")

No. of malignant cases:  357
No. of benign cases:  212


<IPython.core.display.Javascript object>

In [26]:
M=data.loc[data['diagnosis']=='M',:]
M.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [27]:
B=data.loc[data['diagnosis']=='B',:]
B.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
19         B       13.540         14.36           87.46      566.3   
20         B       13.080         15.71           85.63      520.0   
21         B        9.504         12.44           60.34      273.9   
37         B       13.030         18.42           82.61      523.8   
46         B        8.196         16.84           51.71      201.9   

    smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
19          0.09779           0.08129         0.06664             0.047810   
20          0.10750           0.12700         0.04568             0.031100   
21          0.10240           0.06492         0.02956             0.020760   
37          0.08983           0.03766         0.02562             0.029230   
46          0.08600           0.05943         0.01588             0.005917   

    symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
19         0.1885  ...        15.110          19.26            99.70   
20         0.1967  ...        14.500          20.49            96.09   
21         0.1815  ...        10.230          15.66            65.13   
37         0.1467  ...        13.300          22.81            84.46   
46         0.1769  ...         8.964          21.96            57.26   

    area_worst  smoothness_worst  compactness_worst  concavity_worst  \
19       711.2           0.14400            0.17730          0.23900   
20       630.5           0.13120            0.27760          0.18900   
21       314.9           0.13240            0.11480          0.08867   
37       545.9           0.09701            0.04619          0.04833   
46       242.2           0.12970            0.13570          0.06880   

    concave points_worst  symmetry_worst  fractal_dimension_worst  
19               0.12880          0.2977                  0.07259  
20               0.07283          0.3184                  0.08183  
21               0.06227          0.2450                  0.07773  
37               0.05013          0.1987                  0.06169  
46               0.02564          0.3105                  0.07409  

[5 rows x 31 columns]

In [28]:
M=M.drop(['diagnosis'],axis=1)
B=B.drop(['diagnosis'],axis=1)

In [29]:
M.describe()

radius_mean  texture_mean  perimeter_mean    area_mean  \
count   212.000000    212.000000      212.000000   212.000000   
mean     17.462830     21.604906      115.365377   978.376415   
std       3.203971      3.779470       21.854653   367.937978   
min      10.950000     10.380000       71.900000   361.600000   
25%      15.075000     19.327500       98.745000   705.300000   
50%      17.325000     21.460000      114.200000   932.000000   
75%      19.590000     23.765000      129.925000  1203.750000   
max      28.110000     39.280000      188.500000  2501.000000   

       smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
count       212.000000        212.000000      212.000000           212.000000   
mean          0.102898          0.145188        0.160775             0.087990   
std           0.012608          0.053987        0.075019             0.034374   
min           0.073710          0.046050        0.023980             0.020310   
25%           0.094010          0.109600        0.109525             0.064620   
50%           0.102200          0.132350        0.151350             0.086280   
75%           0.110925          0.172400        0.203050             0.103175   
max           0.144700          0.345400        0.426800             0.201200   

       symmetry_mean  fractal_dimension_mean  ...  radius_worst  \
count     212.000000              212.000000  ...    212.000000   
mean        0.192909                0.062680  ...     21.134811   
std         0.027638                0.007573  ...      4.283569   
min         0.130800                0.049960  ...     12.840000   
25%         0.174050                0.056598  ...     17.730000   
50%         0.189900                0.061575  ...     20.590000   
75%         0.209850                0.067075  ...     23.807500   
max         0.304000                0.097440  ...     36.040000   

       texture_worst  perimeter_worst   area_worst  smoothness_worst  \
count     212.000000       212.000000   212.000000        212.000000   
mean       29.318208       141.370330  1422.286321          0.144845   
std         5.434804        29.457055   597.967743          0.021870   
min        16.670000        85.100000   508.100000          0.088220   
25%        25.782500       119.325000   970.300000          0.130475   
50%        28.945000       138.000000  1303.000000          0.143450   
75%        32.690000       159.800000  1712.750000          0.155975   
max        49.540000       251.200000  4254.000000          0.222600   

       compactness_worst  concavity_worst  concave points_worst  \
count         212.000000       212.000000            212.000000   
mean            0.374824         0.450606              0.182237   
std             0.170372         0.181507              0.046308   
min             0.051310         0.023980              0.028990   
25%             0.244475         0.326425              0.152750   
50%             0.356350         0.404900              0.182000   
75%             0.447850         0.556175              0.210675   
max             1.058000         1.170000              0.291000   

       symmetry_worst  fractal_dimension_worst  
count      212.000000               212.000000  
mean         0.323468                 0.091530  
std          0.074685                 0.021553  
min          0.156500                 0.055040  
25%          0.276500                 0.076302  
50%          0.310300                 0.087600  
75%          0.359225                 0.102625  
max          0.663800                 0.207500  

[8 rows x 30 columns]

In [30]:
plt.subplots(figsize=(15,45))
sns.set_style('darkgrid')
plt.subplots_adjust (hspace=0.4, wspace=0.2)
i=0
for col in M.columns:
    i+=1
    plt.subplot(10,3,i)
    # first (0th) column of M is diagnosis, non-numerical
    sns.distplot(M[col],color='m',label='Malignant',hist=False, rug=True)
    sns.distplot(B[col],color='b',label='Benign',hist=False, rug=True)
    plt.legend(loc='upper right')
    plt.title(col)

<IPython.core.display.Javascript object>

In [31]:
sns.set(style="white")
fig,ax=plt.subplots(figsize=(18,18))
corr=data.corr()
mask = np.zeros_like(corr)
mask[np.triu_indices_from(mask)] = True
#cmap = sns.diverging_palette(220, 10, as_cmap=True)
sns.heatmap(corr,vmin=-1,vmax=1,fmt = ".2f",annot=True,cmap="coolwarm", mask=mask, square=True)

<IPython.core.display.Javascript object>

<AxesSubplot:>

In [18]:
#new_data = data.drop(columns=['area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean', 'symmetry_mean', 
         #                   'fractal_dimension_mean','texture_se', 'perimeter_se', 'smoothness_se','compactness_se', 
         #                   'concavity_se', 'concave points_se', 'symmetry_se','fractal_dimension_se', 'texture_worst',
          #                  'smoothness_worst','compactness_worst', 'concavity_worst', 'concave points_worst','symmetry_worst', 
           #                 'fractal_dimension_worst'])

In [32]:
new_data = data.drop(columns=['perimeter_mean','smoothness_mean', 'compactness_mean',
                              'symmetry_mean', 'fractal_dimension_mean','radius_se', 'texture_se', 'perimeter_se', 
                              'area_se', 'smoothness_se','compactness_se', 'concavity_se', 'concave points_se', 
                              'symmetry_se','fractal_dimension_se', 'radius_worst', 'area_worst', 'smoothness_worst',
                              'compactness_worst', 'concavity_worst','symmetry_worst', 'fractal_dimension_worst'])

In [33]:
print(new_data)


    diagnosis  radius_mean  texture_mean  area_mean  concavity_mean  \
0           M        17.99         10.38     1001.0         0.30010   
1           M        20.57         17.77     1326.0         0.08690   
2           M        19.69         21.25     1203.0         0.19740   
3           M        11.42         20.38      386.1         0.24140   
4           M        20.29         14.34     1297.0         0.19800   
..        ...          ...           ...        ...             ...   
564         M        21.56         22.39     1479.0         0.24390   
565         M        20.13         28.25     1261.0         0.14400   
566         M        16.60         28.08      858.1         0.09251   
567         M        20.60         29.33     1265.0         0.35140   
568         B         7.76         24.54      181.0         0.00000   

     concave points_mean  texture_worst  perimeter_worst  concave points_worst  
0                0.14710          17.33           184.60          

In [34]:
new_data.columns

Index(['diagnosis', 'radius_mean', 'texture_mean', 'area_mean',
       'concavity_mean', 'concave points_mean', 'texture_worst',
       'perimeter_worst', 'concave points_worst'],
      dtype='object')

In [35]:
new_data.shape


(569, 9)

In [36]:
new_data.describe()


radius_mean  texture_mean    area_mean  concavity_mean  \
count   569.000000    569.000000   569.000000      569.000000   
mean     14.127292     19.289649   654.889104        0.088799   
std       3.524049      4.301036   351.914129        0.079720   
min       6.981000      9.710000   143.500000        0.000000   
25%      11.700000     16.170000   420.300000        0.029560   
50%      13.370000     18.840000   551.100000        0.061540   
75%      15.780000     21.800000   782.700000        0.130700   
max      28.110000     39.280000  2501.000000        0.426800   

       concave points_mean  texture_worst  perimeter_worst  \
count           569.000000     569.000000       569.000000   
mean              0.048919      25.677223       107.261213   
std               0.038803       6.146258        33.602542   
min               0.000000      12.020000        50.410000   
25%               0.020310      21.080000        84.110000   
50%               0.033500      25.410000        97.660000   
75%               0.074000      29.720000       125.400000   
max               0.201200      49.540000       251.200000   

       concave points_worst  
count            569.000000  
mean               0.114606  
std                0.065732  
min                0.000000  
25%                0.064930  
50%                0.099930  
75%                0.161400  
max                0.291000

In [37]:
new_M=new_data.loc[data['diagnosis']=='M',:]
new_M.head()


diagnosis  radius_mean  texture_mean  area_mean  concavity_mean  \
0         M        17.99         10.38     1001.0          0.3001   
1         M        20.57         17.77     1326.0          0.0869   
2         M        19.69         21.25     1203.0          0.1974   
3         M        11.42         20.38      386.1          0.2414   
4         M        20.29         14.34     1297.0          0.1980   

   concave points_mean  texture_worst  perimeter_worst  concave points_worst  
0              0.14710          17.33           184.60                0.2654  
1              0.07017          23.41           158.80                0.1860  
2              0.12790          25.53           152.50                0.2430  
3              0.10520          26.50            98.87                0.2575  
4              0.10430          16.67           152.20                0.1625

In [38]:
new_B=new_data.loc[data['diagnosis']=='B',:]
new_B.head()


diagnosis  radius_mean  texture_mean  area_mean  concavity_mean  \
19         B       13.540         14.36      566.3         0.06664   
20         B       13.080         15.71      520.0         0.04568   
21         B        9.504         12.44      273.9         0.02956   
37         B       13.030         18.42      523.8         0.02562   
46         B        8.196         16.84      201.9         0.01588   

    concave points_mean  texture_worst  perimeter_worst  concave points_worst  
19             0.047810          19.26            99.70               0.12880  
20             0.031100          20.49            96.09               0.07283  
21             0.020760          15.66            65.13               0.06227  
37             0.029230          22.81            84.46               0.05013  
46             0.005917          21.96            57.26               0.02564

In [39]:
new_M=new_M.drop(['diagnosis'],axis=1)
new_B=new_B.drop(['diagnosis'],axis=1)


In [40]:
X = new_data.values[:, 1:]
print(X)


[[17.99 10.38 1001.0 ... 17.33 184.6 0.2654]
 [20.57 17.77 1326.0 ... 23.41 158.8 0.186]
 [19.69 21.25 1203.0 ... 25.53 152.5 0.243]
 ...
 [16.6 28.08 858.1 ... 34.12 126.7 0.1418]
 [20.6 29.33 1265.0 ... 39.42 184.6 0.265]
 [7.76 24.54 181.0 ... 30.37 59.16 0.0]]


In [41]:
y= new_data['diagnosis']
print(y)


0      M
1      M
2      M
3      M
4      M
      ..
564    M
565    M
566    M
567    M
568    B
Name: diagnosis, Length: 569, dtype: object


In [42]:
r1= new_data['diagnosis'].replace({'B': 0, 'M': 1})
print(r1)



0      1
1      1
2      1
3      1
4      1
      ..
564    1
565    1
566    1
567    1
568    0
Name: diagnosis, Length: 569, dtype: int64


In [43]:
X_train,X_test,y_train, y_test=train_test_split(X, r1, test_size=0.2, random_state=100)

In [44]:
scaler=StandardScaler()
X1_train_std=scaler.fit_transform(X_train)
X1_test_std=scaler.transform(X_test)

In [45]:
#SVM classifier
classifier1 = SVC(kernel='linear')

classifier1.fit(X_train, y_train)
y1_pred = classifier1.predict(X_test)
print("Accuracy for SVM:", accuracy_score(y_test, y1_pred))
print()
print(classification_report(y_test, y1_pred))



Accuracy for SVM: 0.956140350877193

              precision    recall  f1-score   support

           0       0.97      0.95      0.96        65
           1       0.94      0.96      0.95        49

    accuracy                           0.96       114
   macro avg       0.95      0.96      0.96       114
weighted avg       0.96      0.96      0.96       114



In [46]:
#KNN classifier
classifier2 = KNeighborsClassifier(n_neighbors=3 )

# model training
classifier2.fit(X_train,y_train)

# testing the model
y2_pred= classifier2.predict(X_test)
# printing accuracy
print("Accuracy for KNN:", accuracy_score(y_test,y2_pred))
print()
print(classification_report(y_test, y2_pred))



Accuracy for KNN: 0.9122807017543859

              precision    recall  f1-score   support

           0       0.94      0.91      0.92        65
           1       0.88      0.92      0.90        49

    accuracy                           0.91       114
   macro avg       0.91      0.91      0.91       114
weighted avg       0.91      0.91      0.91       114



In [47]:
#Naive Bayes classifier
classifier3 = GaussianNB()

# training the model
classifier3.fit(X_train, y_train)

# testing the model
y3_pred = classifier3.predict(X_test)
print("Accuracy for Naive Bayes: ", accuracy_score(y_test,y3_pred))
print()
print(classification_report(y_test, y3_pred))

Accuracy for Naive Bayes:  0.9385964912280702

              precision    recall  f1-score   support

           0       0.94      0.95      0.95        65
           1       0.94      0.92      0.93        49

    accuracy                           0.94       114
   macro avg       0.94      0.94      0.94       114
weighted avg       0.94      0.94      0.94       114



In [48]:
#Random Forest classifier
classifier4 = RandomForestClassifier()

# fit the model
classifier4.fit(X_train, y_train)

y4_pred = classifier4.predict(X_test)
print("Accuracy score for Random forest:", accuracy_score(y_test,y4_pred))
print()
print(classification_report(y_test, y4_pred))

Accuracy score for Random forest: 0.9736842105263158

              precision    recall  f1-score   support

           0       0.97      0.98      0.98        65
           1       0.98      0.96      0.97        49

    accuracy                           0.97       114
   macro avg       0.97      0.97      0.97       114
weighted avg       0.97      0.97      0.97       114



In [49]:
voting_clf = VotingClassifier(estimators = [('svm',classifier1 ), ('knn', classifier2 ),
                                            ('nb', classifier3),('rf', classifier4)], voting = 'hard')
voting_clf.fit(X_train, y_train)


VotingClassifier(estimators=[('svm', SVC(kernel='linear')),
                             ('knn', KNeighborsClassifier(n_neighbors=3)),
                             ('nb', GaussianNB()),
                             ('rf', RandomForestClassifier())])

In [50]:
predictions = voting_clf.predict(X_test)
print(classification_report(y_test,predictions))
print(accuracy_score(y_test,predictions))

              precision    recall  f1-score   support

           0       0.97      0.98      0.98        65
           1       0.98      0.96      0.97        49

    accuracy                           0.97       114
   macro avg       0.97      0.97      0.97       114
weighted avg       0.97      0.97      0.97       114

0.9736842105263158


In [51]:
pickle.dump(voting_clf,open('model.pkl','wb'))
model=pickle.load(open('model.pkl','rb'))

In [52]:
X_train, y_train.values

(array([[13.05, 19.31, 527.2, ..., 22.25, 90.24, 0.01111],
        [12.88, 28.92, 514.3, ..., 35.74, 88.84, 0.06493],
        [15.75, 19.22, 758.6, ..., 24.17, 119.4, 0.2135],
        ...,
        [11.66, 17.07, 421.0, ..., 19.74, 83.61, 0.04262],
        [12.86, 18.0, 506.3, ..., 24.82, 91.88, 0.07926],
        [9.295, 13.9, 257.8, ..., 17.84, 67.84, 0.07262]], dtype=object),
 array([0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
        0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
        0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,
        0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
        0, 1, 1, 1, 0, 0, 1,